lang: en-us
title: Arhip Storozhev
author: Arhip Storozhev
theme: mystyle.css
baseurl: ""

menu:
  - title: blog
    url: /blog.html
  - title: archive
    url: /archive.html

sections:
  - id: blog
    title: "Latest Posts"

bottom_sections:
  - title: "Projects"
    items:
      - title: Luna SSG
        url: https://github.com/luna-ssg/luna-ssg
        description: "Fast and simple static site generator with blog support (used for this site)"
      - title: Belinsky Library Education Hub
        url: https://github.com/stornov/library-education-hub
        description: "An inclusive SPA platform for adults aged 55 and older"

footer:
  - title: Contacts
    links:
      - text: Arhip Storozhev
        url: null
      - text: arsestordev@gmail.com
        url: mailto:arsestordev@gmail.com
  - title: Socials
    links:
      - text: GitHub
        url: https://github.com/stornov
  - title: Powered by
    links:
      - text: Luna SSG
        url: https://github.com/luna-ssg/luna-ssg